---
mqtt:
  hostname: test.mosquitto.org
  portnumber: 1883
  username: projuser
  password: NOPENOPENOPE
  topic:
    name: "Sample Projector"
    prefix: projectionist
    node_id: HOSTNAME
    object_id: tk850
    unique_id: tk850_sample
  discovery:
    prefix: homeassistant
  keepalive: 120
  useTLS: false
serial_port:
  name: /dev/ttyUSB0
  baud: 9600
  timeout: 5
worker:
  delay: 60
device:
  manufacturer: BENQ
  model: TK850
  suggested_area: "Sample Room"
