---
mqtt:
  hostname: test.mosquitto.org
  portnumber: 1883
  username: projuser
  password: NOPENOPENOPE
  topicPrefix: tk850
  keepalive: 120
  useTLS: false
serialPort:
  name: /dev/ttyUSB0
  baud: 9600
